version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./back/config/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www
      - ./coverage/lcov-report:/var/coverage

  postgres-dev:
    image: postgres:latest
    container_name: postgres_dev_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
      PGDATA: /data/postgres
    ports:
      - 5433:5432
    volumes:
       - postgres-dev:/data/postgres

  postgres-test:
    image: postgres:latest
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
      PGDATA: /data/postgres
    ports:
      - 5434:5432
    volumes:
       - postgres-test:/data/postgres

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      volumes:
        - pgadmin:/var/lib/pgadmin
        - ./back/config/docker_pgadmin_servers.json:/pgadmin4/servers.json
      depends_on:
        - postgres-dev
        - postgres-test

  redis:
    image: redis:latest
    ports:
      - 6378:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
    postgres-dev:
    postgres-test:
    pgadmin: